[theme]
# Keep original beautiful gradient theme
primaryColor = "#667eea"
backgroundColor = "#1e1e1e"
secondaryBackgroundColor = "#2d2d2d"
textColor = "#ffffff"

[server]
# Server settings
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
# Browser settings
gatherUsageStats = false

[ui]
# Hide Streamlit branding
hideTopBar = true
hideSidebarNav = false
